server:
  port: 8008
spring:
  datasource:
    url: jdbc:mysql://192.168.2.64:3306/base_test?useUnicode=true&characterEncoding=UTF-8&useTimezone=true&serverTimezone=GMT%2b8&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000   #不能小于30秒，否则默认回到1800秒
      connection-test-query: SELECT 1
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
  redis:
    host: 127.0.0.1
    port: 6379
    #    cluster:
    #      nodes: 47.98.53.46:6382,47.98.53.46:6381,47.98.53.46:6380,47.98.53.46:6379
    #      max-redirects: 6
    timeout: 10000 #客户端超时时间单位是毫秒 默认是2000
    maxIdle: 300 #最大空闲数
    maxTotal: 1000 #控制一个pool可分配多少个jedis实例,用来替换上面的redis.maxActive,如果是jedis 2.4以后用该属性
    maxWaitMillis: 1000 #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
    minEvictableIdleTimeMillis: 300000 #连接的最小空闲时间 默认1800000毫秒(30分钟)
    numTestsPerEvictionRun: 1024 #每次释放连接的最大数目,默认3
    timeBetweenEvictionRunsMillis: 30000 #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
    testOnBorrow: true #是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
    testWhileIdle: true #在空闲时检查有效性, 默认false
#mybatis
mybatis-plus:
  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.zenvans.kkframe.entity.sys
  #,com.zenvans.zvplat.entity.common
 # typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: UUID
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    #刷新mapper 调试神器
    refresh: false
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

logging:
  config: classpath:logback-spring.xml
  level:
    org.example.web.mapper: debug

#设置session超时时间,毫秒为单位，保存5个小时
shiro :
  session:
   timeout: 18000 000

#定义一些常量
